### ISSUE TITLE
Unsupported Modules Detected: Compilation is not supported for following modules: body_pix. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project

### ISSUE THREAD

**Issue by pfnuneu** [hegman12/body_pix_tflite#1]
Hi hegman12
Thank you for the work done, i also need bodyPix for my project (Android) but currently i can't build the android project.  This is the error i get 
"Unsupported Modules Detected: Compilation is not supported for following modules: body_pix. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project" any suggestion.

**Comment by hegman12** [comment]
Hi pfnuneu,
Thanks for trying this out! If I understand correctly, you are developing native android application. This is a flutter plugin project and cant be directly used in android native project. However, you can check out the method `private HashMap<String,Object> runInference(Bitmap uint8InImage, float internal_resolution,float out_stride,int rotate, float threshold )` [here ](https://github.com/hegman12/body_pix_tflite/blob/master/android/src/main/java/com/bodypix/body_pix/BodyPixPlugin.java) and copy it to your project. You will also need to add below to your app dependencies(app build.gradle).

`
dependencies {
    implementation('org.tensorflow:tensorflow-lite:2.2.0') { changing = true }
    implementation('org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly') { changing = true }
    implementation('org.tensorflow:tensorflow-lite-support:0.0.0-nightly') { changing = true }
    // For tensorflowlite select OP support
    implementation ('org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly') { changing = true }
}
`

and below code under android in build.gradle

`
aaptOptions {
        noCompress "tflite"
    }
`

And then add the tflite model [here ](https://github.com/hegman12/body_pix_tflite/tree/master/converter_example/tflite/converted)file to your assets.

Good luck!

**Comment by hegman12** [comment]
Hi, I hope that helped. I am closing this request for now, feel free to reopen if you have issues!
