### ISSUE TITLE
How to get coloured segmentation on native android

### ISSUE THREAD

**Issue by AngryDuckFTW** [hegman12/body_pix_tflite#2]
Hi I am having a look at this project, but not using flutter so I can't just run your code. I have all the niecesary java files and got it running. But after running "runInference()" it gives back an array of -1 or 1. 

So just a white a black black image of the person in the image. Im wondering what function you're calling in order to get the different body sections like you showed in the screenshot? 

could you point me to the location of the code to run for this segmentation process and also advice what all the custom tensor operator Java files are for as I can't figure out how they're used or what they're meant to do.

Thanks

**Comment by hegman12** [comment]
Hi, thanks for your interest in using the model. You can use `runInference` method, it returns `HashMap<String,Object>`. If you access the items of this HashMap with key `parts`, you will get `byte[]` of length `new_height * new_width` (both new_height and new_width are items in the HashMap). This is where you get parts segmentation. You can convert this `byte[]` to `int[]` each int consumes 1 byte. The possible values for this int array is 0-23 and 255. 255 represents the background pixel, and other values represents corresponding parts at that pixel position. You will need to convert this raw pixels into `Bitmap`(currently, this code is in flutter).

You can ignore the other tensor operators. They are not used. I wrote it because I was using original bodypix model from Google. Then I realized not all the transformations used in original bodypix project(tfjs) are supported in android. Then I rewrote those in python and baked those transformations into tflite model itself. This simplified the code in java.

Let me know if you are stuck or need more information, happy to help!

**Comment by AngryDuckFTW** [comment]
Thanks for the detailed answer @hegman12! ill take a look now

**Comment by Charlesjean** [comment]
> Thanks for the detailed answer @hegman12! ill take a look now

@AngryDuckFTW , Do you successfully get the colored segmentation image? I am also trying to do this.

**Comment by Charlesjean** [comment]
> Hi, thanks for your interest in using the model. You can use `runInference` method, it returns `HashMap<String,Object>`. If you access the items of this HashMap with key `parts`, you will get `byte[]` of length `new_height * new_width` (both new_height and new_width are items in the HashMap). This is where you get parts segmentation. You can convert this `byte[]` to `int[]` each int consumes 1 byte. The possible values for this int array is 0-23 and 255. 255 represents the background pixel, and other values represents corresponding parts at that pixel position. You will need to convert this raw pixels into `Bitmap`(currently, this code is in flutter).
> 
> You can ignore the other tensor operators. They are not used. I wrote it because I was using original bodypix model from Google. Then I realized not all the transformations used in original bodypix project(tfjs) are supported in android. Then I rewrote those in python and baked those transformations into tflite model itself. This simplified the code in java.
> 
> Let me know if you are stuck or need more information, happy to help!

Great, I can get the segmentation using this method.

**Comment by Charlesjean** [comment]
> Hi, thanks for your interest in using the model. You can use `runInference` method, it returns `HashMap<String,Object>`. If you access the items of this HashMap with key `parts`, you will get `byte[]` of length `new_height * new_width` (both new_height and new_width are items in the HashMap). This is where you get parts segmentation. You can convert this `byte[]` to `int[]` each int consumes 1 byte. The possible values for this int array is 0-23 and 255. 255 represents the background pixel, and other values represents corresponding parts at that pixel position. You will need to convert this raw pixels into `Bitmap`(currently, this code is in flutter).
> 
> You can ignore the other tensor operators. They are not used. I wrote it because I was using original bodypix model from Google. Then I realized not all the transformations used in original bodypix project(tfjs) are supported in android. Then I rewrote those in python and baked those transformations into tflite model itself. This simplified the code in java.
> 
> Let me know if you are stuck or need more information, happy to help!

I found "255 represents the background pixel" is not the case, actually -1 represents the background pixel.

**Comment by Charlesjean** [comment]
> Hi, thanks for your interest in using the model. You can use `runInference` method, it returns `HashMap<String,Object>`. If you access the items of this HashMap with key `parts`, you will get `byte[]` of length `new_height * new_width` (both new_height and new_width are items in the HashMap). This is where you get parts segmentation. You can convert this `byte[]` to `int[]` each int consumes 1 byte. The possible values for this int array is 0-23 and 255. 255 represents the background pixel, and other values represents corresponding parts at that pixel position. You will need to convert this raw pixels into `Bitmap`(currently, this code is in flutter).
> 
> You can ignore the other tensor operators. They are not used. I wrote it because I was using original bodypix model from Google. Then I realized not all the transformations used in original bodypix project(tfjs) are supported in android. Then I rewrote those in python and baked those transformations into tflite model itself. This simplified the code in java.
> 
> Let me know if you are stuck or need more information, happy to help!

I found "255 represents the background pixel" is not the case, actually -1 represents the background pixel. When you cast 255 to byte, the result will be -1.

**Comment by hegman12** [comment]
@Charlesjean  yes, in java it is -1. But when -1 is caste to UINT8LIST in dart, it will be converted to 255 as below.

`-1 & 0xFF`
